version: '3.7'
services: 
    api:
        container_name: 'go-comments'
        build: '.'
        ports:
            - '3000:3000'
        depends_on: 
            - 'mongo'
        restart: 'always'
    mongo:
        image: 'mongo:latest'
        container_name: 'mongo'
        ports:
            - '27017:27017'